### ISSUE TITLE
legacy_id plugin crash

### ISSUE THREAD

**Issue by note3crafter** [NukkitX/SynapsePM#18]
PocketMine-MP Crash Dump Mon Aug 5 15:17:52 UTC 2019

Error: Undefined index: legacy_id
File: src/pocketmine/network/mcpe/protocol/StartGamePacket
Line: 301
Type: ErrorException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: SynapsePM v1.1.0

Code:
[292] 		$this->putString($this->multiplayerCorrelationId);
[293] 	}
[294] 
[295] 	private static function serializeBlockTable(array $table) : string{
[296] 		$stream = new NetworkBinaryStream();
[297] 		$stream->putUnsignedVarInt(count($table));
[298] 		foreach($table as $v){
[299] 			$stream->putString($v["name"]);
[300] 			$stream->putLShort($v["data"]);
[301] 			$stream->putLShort($v["legacy_id"]);
[302] 		}
[303] 		return $stream->getBuffer();
[304] 	}
[305] 
[306] 	private static function serializeItemTable(array $table) : string{
[307] 		$stream = new NetworkBinaryStream();
[308] 		$stream->putUnsignedVarInt(count($table));
[309] 		foreach($table as $name => $legacyId){
[310] 			$stream->putString($name);
[311] 			$stream->putLShort($legacyId);

Backtrace:
#0 src/pocketmine/network/mcpe/protocol/StartGamePacket(301): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[26] Undefined index: legacy_id, string[95] phar:///home/CityBuild/pocketmine.phar/src/pocketmine/network/mcpe/protocol/Star, integer 301, array[3])
#1 src/pocketmine/network/mcpe/protocol/StartGamePacket(277): pocketmine\network\mcpe\protocol\StartGamePacket::serializeBlockTable(array[3311])
#2 src/pocketmine/network/mcpe/protocol/DataPacket(110): pocketmine\network\mcpe\protocol\StartGamePacket->encodePayload()
#3 plugins/SynapsePM-master/src/synapsepm/network/SynLibInterface(49): pocketmine\network\mcpe\protocol\DataPacket->encode()
#4 src/pocketmine/Player(3182): synapsepm\network\SynLibInterface->putPacket(object synapsepm\Player, object pocketmine\network\mcpe\protocol\StartGamePacket, boolean , boolean )
#5 plugins/SynapsePM-master/src/synapsepm/Player(141): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\StartGamePacket, boolean , boolean )
#6 src/pocketmine/Player(3202): synapsepm\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\StartGamePacket, boolean , boolean )
#7 src/pocketmine/Player(2158): pocketmine\Player->dataPacket(object pocketmine\network\mcpe\protocol\StartGamePacket)
#8 plugins/SynapsePM-master/src/synapsepm/Player(222): pocketmine\Player->completeLoginSequence()
#9 src/pocketmine/Player(2100): synapsepm\Player->completeLoginSequence()
#10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(126): pocketmine\Player->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
#11 src/pocketmine/network/mcpe/protocol/ResourcePackClientResponsePacket(62): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
#12 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
#13 src/pocketmine/Player(3126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
#14 plugins/SynapsePM-master/src/synapsepm/Player(88): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
#15 plugins/SynapsePM-master/src/synapsepm/Synapse(285): synapsepm\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
#16 plugins/SynapsePM-master/src/synapsepm/network/SynapseInterface(93): synapsepm\Synapse->handleDataPacket(object synapsepm\network\protocol\spp\RedirectPacket)
#17 plugins/SynapsePM-master/src/synapsepm/network/SynapseInterface(62): synapsepm\network\SynapseInterface->handlePacket(string[23] .#54....ZG.<Y..G.......)
#18 plugins/SynapsePM-master/src/synapsepm/Synapse(155): synapsepm\network\SynapseInterface->process()
#19 plugins/SynapsePM-master/src/synapsepm/Synapse(82): synapsepm\Synapse->tick()
#20 src/pocketmine/scheduler/TaskHandler(159): class@anonymous /home/CityBuild/plugins/SynapsePM-master/src/synapsepm/Synapse.php0x7f9e08fea8f9->onRun(integer 1031)
#21 src/pocketmine/scheduler/TaskScheduler(199): pocketmine\scheduler\TaskHandler->run(integer 1031)
#22 src/pocketmine/plugin/PluginManager(689): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1031)
#23 src/pocketmine/Server(2569): pocketmine\plugin\PluginManager->tickSchedulers(integer 1031)
#24 src/pocketmine/Server(2345): pocketmine\Server->tick()
#25 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
#26 src/pocketmine/Server(1784): pocketmine\Server->start()
#27 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/CityBuild/, string[24] /home/CityBuild/plugins/)
#28 (1): require(string[68] phar:///home/CityBuild/pocketmine.phar/src/pocketmine/PocketMine.php)

**Comment by note3crafter** [comment]
Can you try to fix it its crashing wen im joining the server

**Comment by Josewowgame2888** [comment]
https://github.com/Josewowgame2888/SynapsePM
