### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by Reflyansyah** [NukkitX/SynapsePM#2]
What is this ?
What is the function

**Comment by Creeperface01** [comment]
Synapse is nemisys client. And nemisys is a proxy for fast transfer between servers

**Comment by Reflyansyah** [comment]
How to use ?

**Comment by Reflyansyah** [comment]
NemiSys : Current SPP version: 8
SnynapsePM : Current SPP version: 10
Can it synapse Version 10 connect to Nemisys V 8

**Comment by Creeperface01** [comment]
Use discord
