### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by majovec** [NukkitX/SynapsePM#3]
Hello, I have such a problem when I connect to the main server so everything works well but when I connect to the test server I can not move or write anything 

Video: 
https://youtu.be/TAHWmdlrPZM

**Comment by majovec** [comment]
@CreeperFace01 do you know where is problem?

**Comment by majovec** [comment]
@CreeperFace01 You can throw your personal disputes now. This is about helping more people. It does not mean that there is a dispute between us so that everyone will get it

**Comment by GamakCZ** [comment]
for me it works 😅
