### ISSUE TITLE
Add SynapsePM::getInstance() for easier working with API

### ISSUE THREAD

**Issue by justin-eckenweber** [NukkitX/SynapsePM#8]
My suggestion for SynapsePM is:
Add the ability to do SynapsePM::getInstance()
So you can easily do SynapsePM::getInstance()->doThis()

EconomyAPI is an good example for this: https://github.com/poggit-orphanage/EconomyS/tree/master/EconomyAPI

**Comment by boi1216** [comment]
Why multiple instances? You can get SynapsePM instance using PluginManager.

**Comment by justin-eckenweber** [comment]
It's easier to use.
